#!/bin/bash

# gnucash-dev-docker: Docker containers for automated OS setup and dev/build environ for gnucash v3+ binaries and docs
# Copyright (C) 2019 Dale Phurrough <dale@hidale.com>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

if [ "$IGNORE_BUILD_FAILURE" != "1" ]; then
    set -e
fi

# add perl script directories to path
. /etc/profile

# Enable dbus functionality with a machine-id
dbus-uuidgen --ensure

# TODO compile and install an X11-enabled dbus-launch, the package in Arch repos have X11 disabled
# https://www.reddit.com/r/archlinux/comments/50zbdt/dbus_no_longer_compiled_with_x11_support/
# Without this, you may get warnings on start of gnucash similar to:
#      dconf-WARNING **: 11:45:14.006: failed to commit changes to dconf: Error spawning command
#      line “dbus-launch --autolaunch=f8b41aabbccddee068a50123456712c2 --binary-syntax --close-stderr”: Child process exited with code 1

. /commonbuild
