#!/bin/bash

# gnucash-dev-docker: Docker containers for automated OS setup and dev/build environ for GnuCash v3+ binaries and docs
# Copyright (C) 2019 Dale Phurrough <dale@hidale.com>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

if [ "$GNC_IGNORE_BUILD_FAIL" != "1" ]; then
    set -e
fi

# prepare source directory
mkdir -p /gnucash
if [ -z "$(ls -A /gnucash)" ]; then
    if [ -n "$GNC_GIT_CHECKOUT" ]; then
        git clone -n https://github.com/Gnucash/gnucash.git
        cd /gnucash && git checkout "$GNC_GIT_CHECKOUT"
        cd /
    else
        echo 'Nothing to do because $GNC_GIT_CHECKOUT is undefined and /gnucash is empty'
        exit 1
    fi
fi

# prepare build directory
mkdir -p /build
cd /build

# prepare user settings directory
mkdir -p "$HOME"/.local/share

# patch CMakefile to remove forced 'mt' in Boost library pathname search; it only affects the file search, not Boost functionality
# https://askubuntu.com/questions/486006/cannot-find-boost-thread-mt-library?answertab=votes#tab-top
sed -i -e '/Boost_USE_MULTITHREADED ON/c #removed problematic Boost_USE_MULTITHREADED ON' /gnucash/CMakeLists.txt

# necessary for some Linux (e.g. CentOS) that have non-standard Boost library pathnames
# e.g. libary files named 'libboost_regex.so.1.69.0' need removal of forced multithread path search in the root CMakeLists.txt and
#      -DBoost_COMPILER=.so.1.69.0 -DBoost_NAMESPACE=libboost -DBoost_USE_MULTITHREADED=OFF
if [[ -n "$(compgen -G '/usr/lib64/libboost_regex.so.*')" && ! -f '/usr/lib64/libboost_regex.so' ]]; then
    _GNC_CMAKE_COMPAT="-DBoost_COMPILER=$(find /usr/lib64 -name 'libboost_regex.so*' ! -type l | grep -o -E '\.so.*') -DBoost_NAMESPACE=libboost -DBoost_USE_MULTITHREADED=OFF"
fi

# enable minimal translation support when OS has gettext < 0.19.6
if [ $(((echo '0.19.6'; gettext --version | head -1 | grep -o -E '\b[0-9.]{3,}\b') | sort -V) | head -1) != "0.19.6" ]; then
    _GNC_CMAKE_COMPAT="$_GNC_CMAKE_COMPAT -DALLOW_OLD_GETTEXT=ON"
fi

# enable dbus/dconf/gsettings functionality with a machine-id
dbus-uuidgen --ensure

# execute build and/or test phases
GNC_PHASES="${GNC_PHASES:-build,test}"
if [[ "$BUILDTYPE" == "cmake-make" ]]; then
    [[ "$GNC_PHASES" =~ "build" ]] && cmake $_GNC_CMAKE_COMPAT $PLATFORM_CMAKE_OPTS ../gnucash/ && make -j $(nproc)
    [[ "$GNC_PHASES" =~ "install" ]] && make install
    [[ "$GNC_PHASES" =~ "test" ]] && (make check || . /afterfailure)
elif [[ "$BUILDTYPE" == "cmake-ninja" ]]; then
    [[ "$GNC_PHASES" =~ "build" ]] && cmake -GNinja $_GNC_CMAKE_COMPAT $PLATFORM_CMAKE_OPTS ../gnucash && ninja
    [[ "$GNC_PHASES" =~ "install" ]] && ninja install
    [[ "$GNC_PHASES" =~ "test" ]] && (ninja check || . /afterfailure)
else
    echo "Unknown buildtype: \"$BUILDTYPE\". Not building."
fi

echo "**********************"
echo "* Phase(s) concluded *"
echo "**********************"

if [ "$GNC_EXIT_WITH_RESULT" = "1" ]; then
    exit 0
fi

# prevent container from immediately exiting
#exec tail -f /dev/null
exec bash
