#!/bin/bash -e

# enables minimal translation support when OS has gettext < 0.19.6
if dpkg --compare-versions "$(dpkg-query --showformat='${Version}' --show gettext 2> /dev/null)" lt "0.19.6"; then
    export _GNC_CMAKE_COMPAT=-DALLOW_OLD_GETTEXT=ON
fi

. /commonbuild
